### ISSUE TITLE
Add Framework request

### ISSUE THREAD

**Issue by ThomasGorisse** [mikeroyal/AR-VR-Guide#2]
Hi,

Could you please add us: https://github.com/SceneView/sceneview-android
It's an Android Kotlin SDK for 3D and AR within an app.

Thanks

**Comment by ThomasGorisse** [comment]
The demo app is here https://play.google.com/store/apps/details?id=com.gorisse.thomas.arcamera if you want to see what you can do with it.

**Comment by mikeroyal** [comment]
It's been added.
