### ISSUE TITLE
Photocatch Photogrammetry app for mac silicon processors

### ISSUE THREAD

**Issue by OEOxr** [mikeroyal/AR-VR-Guide#20]
I have another suggestion for photogrammetry list. 

Photocatch app is a light application which uses Object Capture SDK of Apple. (https://developer.apple.com/augmented-reality/object-capture/) Thanks to Apple SDK, it is straightforward and works incomparably fast compare to old photogrammetry tools.

https://apps.apple.com/jp/app/photocatch/id1576081762?l=en

I think this library should include this app and apple object capture SDK.

**Comment by mikeroyal** [comment]
Thanks for the suggestion I'll take a look at it.

**Comment by mikeroyal** [comment]
Okay, a PR was made to add PhotoCatch. Thank you for your suggestion!
